/**
 * Word Export Utility
 * @description Exports editor HTML content to a .docx file
 * @note docx and file-saver are dynamically loaded on demand, downloaded only when exporting
 */
import type {
  Paragraph as ParagraphType,
  Table as TableType,
  TextRun as TextRunType,
  ExternalHyperlink as ExternalHyperlinkType,
  ITableCellOptions,
} from 'docx'

/** Inline text style context */
interface InlineStyle {
  bold: boolean
  italic: boolean
  underline: boolean
  strike: boolean
  code: boolean
  link: string | null
  superscript: boolean
  subscript: boolean
}

const defaultInlineStyle: InlineStyle = {
  bold: false,
  italic: false,
  underline: false,
  strike: false,
  code: false,
  link: null,
  superscript: false,
  subscript: false,
}

/**
 * Export editor HTML to .docx file and download
 * @param html - Editor HTML content
 * @param filename - Filename (without extension)
 */
export async function exportToWord(html: string, filename = 'document'): Promise<void> {
  // Dynamically load docx and file-saver
  const [docx, fileSaverModule] = await Promise.all([
    import('docx'),
    import('file-saver') as Promise<any>,
  ])
  const saveAs: (blob: Blob, name: string) => void =
    fileSaverModule.saveAs ?? fileSaverModule.default?.saveAs ?? fileSaverModule.default

  const {
    Document,
    Paragraph,
    TextRun,
    HeadingLevel,
    AlignmentType,
    Table,
    TableRow,
    TableCell,
    WidthType,
    Packer,
    ExternalHyperlink,
  } = docx

  /** Heading level mapping */
  const HEADING_MAP: Record<string, (typeof HeadingLevel)[keyof typeof HeadingLevel]> = {
    H1: HeadingLevel.HEADING_1,
    H2: HeadingLevel.HEADING_2,
    H3: HeadingLevel.HEADING_3,
    H4: HeadingLevel.HEADING_4,
    H5: HeadingLevel.HEADING_5,
    H6: HeadingLevel.HEADING_6,
  }

  /** Alignment mapping */
  const ALIGN_MAP: Record<string, (typeof AlignmentType)[keyof typeof AlignmentType]> = {
    left: AlignmentType.LEFT,
    center: AlignmentType.CENTER,
    right: AlignmentType.RIGHT,
    justify: AlignmentType.JUSTIFIED,
  }

  /**
   * Parse alignment from HTML element
   */
  function getAlignment(el: Element): (typeof AlignmentType)[keyof typeof AlignmentType] | undefined {
    const style = (el as HTMLElement).style?.textAlign
    if (style && ALIGN_MAP[style]) return ALIGN_MAP[style]
    return undefined
  }

  /**
   * Convert inline node to TextRun array
   */
  function parseInlineNodes(node: Node, style: InlineStyle): (TextRunType | ExternalHyperlinkType)[] {
    const runs: (TextRunType | ExternalHyperlinkType)[] = []

    if (node.nodeType === Node.TEXT_NODE) {
      const text = node.textContent || ''
      if (!text) return runs

      const run = new TextRun({
        text,
        bold: style.bold || undefined,
        italics: style.italic || undefined,
        underline: style.underline ? {} : undefined,
        strike: style.strike || undefined,
        font: style.code ? { name: 'Courier New' } : undefined,
        superScript: style.superscript || undefined,
        subScript: style.subscript || undefined,
      })

      if (style.link) {
        runs.push(
          new ExternalHyperlink({
            children: [
              new TextRun({
                text,
                bold: style.bold || undefined,
                italics: style.italic || undefined,
                underline: {},
                style: 'Hyperlink',
              }),
            ],
            link: style.link,
          }),
        )
      } else {
        runs.push(run)
      }

      return runs
    }

    if (node.nodeType !== Node.ELEMENT_NODE) return runs

    const el = node as Element
    const tag = el.tagName.toUpperCase()

    // Update styles based on tag
    const newStyle = { ...style }
    if (tag === 'STRONG' || tag === 'B') newStyle.bold = true
    if (tag === 'EM' || tag === 'I') newStyle.italic = true
    if (tag === 'U') newStyle.underline = true
    if (tag === 'S' || tag === 'DEL' || tag === 'STRIKE') newStyle.strike = true
    if (tag === 'CODE') newStyle.code = true
    if (tag === 'SUP') newStyle.superscript = true
    if (tag === 'SUB') newStyle.subscript = true
    if (tag === 'A') newStyle.link = el.getAttribute('href')

    // Handle BR tag as break
    if (tag === 'BR') {
      runs.push(new TextRun({ break: 1 }))
      return runs
    }

    for (const child of Array.from(el.childNodes)) {
      runs.push(...parseInlineNodes(child, newStyle))
    }

    return runs
  }

  /**
   * Convert <li> element to paragraph
   */
  function parseListItem(
    li: Element,
    ordered: boolean,
    level: number,
  ): ParagraphType[] {
    const paragraphs: ParagraphType[] = []
    const runs = parseInlineNodes(li, { ...defaultInlineStyle })
    // Filter TextRuns (exclude paragraphs generated by nested lists)
    const textRuns = runs.filter((r): r is TextRunType => r instanceof TextRun || r instanceof ExternalHyperlink)

    if (textRuns.length > 0) {
      paragraphs.push(
        new Paragraph({
          children: textRuns,
          numbering: ordered
            ? { reference: 'ordered-list', level }
            : { reference: 'bullet-list', level },
        }),
      )
    }

    // Handle nested lists
    for (const child of Array.from(li.children)) {
      const childTag = child.tagName.toUpperCase()
      if (childTag === 'UL') {
        paragraphs.push(...parseList(child, false, level + 1))
      } else if (childTag === 'OL') {
        paragraphs.push(...parseList(child, true, level + 1))
      }
    }

    return paragraphs
  }

  /**
   * Convert <ul>/<ol> element to paragraph array
   */
  function parseList(list: Element, ordered: boolean, level = 0): ParagraphType[] {
    const paragraphs: ParagraphType[] = []
    for (const li of Array.from(list.children)) {
      if (li.tagName.toUpperCase() === 'LI') {
        paragraphs.push(...parseListItem(li, ordered, level))
      }
    }
    return paragraphs
  }

  /**
   * Convert table HTML to docx Table
   */
  function parseTable(tableEl: Element): TableType {
    const rows: InstanceType<typeof TableRow>[] = []

    const trElements = tableEl.querySelectorAll('tr')
    for (const tr of Array.from(trElements)) {
      const cells: InstanceType<typeof TableCell>[] = []
      const tdElements = tr.querySelectorAll('td, th')
      for (const td of Array.from(tdElements)) {
        const cellOpts: ITableCellOptions = {
          children: [
            new Paragraph({
              children: parseInlineNodes(td, { ...defaultInlineStyle }) as TextRunType[],
            }),
          ],
          width: { size: 100, type: WidthType.AUTO },
        }
        cells.push(new TableCell(cellOpts))
      }
      if (cells.length > 0) {
        rows.push(new TableRow({ children: cells }))
      }
    }

    return new Table({
      rows,
      width: { size: 100, type: WidthType.PERCENTAGE },
    })
  }

  /**
   * Convert code block to paragraph
   */
  function parseCodeBlock(pre: Element): ParagraphType[] {
    const code = pre.querySelector('code') || pre
    const text = code.textContent || ''
    const lines = text.split('\n')

    return lines.map(
      (line) =>
        new Paragraph({
          children: [
            new TextRun({
              text: line || ' ',
              font: { name: 'Courier New' },
              size: 20,
            }),
          ],
          spacing: { before: 0, after: 0 },
        }),
    )
  }

  /**
   * Parse block HTML node into docx elements
   */
  function parseBlockNodes(container: Element): (ParagraphType | TableType)[] {
    const elements: (ParagraphType | TableType)[] = []

    for (const node of Array.from(container.childNodes)) {
      if (node.nodeType === Node.TEXT_NODE) {
        const text = node.textContent?.trim()
        if (text) {
          elements.push(new Paragraph({ children: [new TextRun({ text })] }))
        }
        continue
      }

      if (node.nodeType !== Node.ELEMENT_NODE) continue

      const el = node as Element
      const tag = el.tagName.toUpperCase()

      // Heading
      if (HEADING_MAP[tag]) {
        const runs = parseInlineNodes(el, { ...defaultInlineStyle })
        elements.push(
          new Paragraph({
            heading: HEADING_MAP[tag],
            children: runs as TextRunType[],
            alignment: getAlignment(el),
          }),
        )
        continue
      }

      // Paragraph
      if (tag === 'P') {
        const runs = parseInlineNodes(el, { ...defaultInlineStyle })
        if (runs.length > 0) {
          elements.push(
            new Paragraph({
              children: runs as TextRunType[],
              alignment: getAlignment(el),
            }),
          )
        } else {
          elements.push(new Paragraph({}))
        }
        continue
      }

      // List
      if (tag === 'UL') {
        elements.push(...parseList(el, false))
        continue
      }
      if (tag === 'OL') {
        elements.push(...parseList(el, true))
        continue
      }

      // Code block
      if (tag === 'PRE') {
        elements.push(...parseCodeBlock(el))
        continue
      }

      // Table
      if (tag === 'TABLE') {
        elements.push(parseTable(el))
        continue
      }

      // Blockquote
      if (tag === 'BLOCKQUOTE') {
        const innerElements = parseBlockNodes(el)
        for (const inner of innerElements) {
          if (inner instanceof Paragraph) {
            elements.push(
              new Paragraph({
                ...((inner as any).options || {}),
                indent: { left: 720 },
                border: {
                  left: { style: 'single' as any, size: 6, color: '999999' },
                },
              }),
            )
          } else {
            elements.push(inner)
          }
        }
        continue
      }

      // Horizontal rule
      if (tag === 'HR') {
        elements.push(
          new Paragraph({
            children: [new TextRun({ text: '─'.repeat(50) })],
            alignment: AlignmentType.CENTER,
          }),
        )
        continue
      }

      // DIV or other container -> recursive
      if (el.children.length > 0) {
        elements.push(...parseBlockNodes(el))
      } else {
        const text = el.textContent?.trim()
        if (text) {
          elements.push(new Paragraph({ children: [new TextRun({ text })] }))
        }
      }
    }

    return elements
  }

  // Parse HTML
  const parser = new DOMParser()
  const doc = parser.parseFromString(html, 'text/html')
  const body = doc.body

  const children = parseBlockNodes(body)

  // Fallback: at least one empty paragraph
  if (children.length === 0) {
    children.push(new Paragraph({}))
  }

  const document = new Document({
    numbering: {
      config: [
        {
          reference: 'bullet-list',
          levels: [
            { level: 0, format: 'bullet', text: '•', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
            { level: 1, format: 'bullet', text: '○', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1440, hanging: 360 } } } },
            { level: 2, format: 'bullet', text: '▪', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 2160, hanging: 360 } } } },
          ],
        },
        {
          reference: 'ordered-list',
          levels: [
            { level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 720, hanging: 360 } } } },
            { level: 1, format: 'lowerLetter', text: '%2.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 1440, hanging: 360 } } } },
            { level: 2, format: 'lowerRoman', text: '%3.', alignment: AlignmentType.LEFT, style: { paragraph: { indent: { left: 2160, hanging: 360 } } } },
          ],
        },
      ],
    },
    sections: [
      {
        children,
      },
    ],
  })

  const blob = await Packer.toBlob(document)
  saveAs(blob, `${filename}.docx`)
}
